version: "3.8"

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/shopcafe-devops-backend:latest
    container_name: shopcafe-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGO_URI}
      - SERVER_PORT=8080
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    image: ${DOCKERHUB_USERNAME}/shopcafe-devops-frontend:latest
    container_name: shopcafe-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
